CREATE ROLE fitness_app WITH LOGIN PASSWORD 'fitness_app_password' NOSUPERUSER NOBYPASSRLS;
GRANT USAGE ON SCHEMA public TO fitness_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO fitness_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO fitness_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fitness_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO fitness_app;
