CREATE ROLE fitness_app WITH LOGIN PASSWORD 'fitness_app_password' NOSUPERUSER NOBYPASSRLS;
GRANT USAGE ON SCHEMA public TO fitness_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fitness_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fitness_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO fitness_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO fitness_app;
