"""update rbac models

Revision ID: 0a561fd73793
Revises: db8f4db0e58d
Create Date: 2026-08-09 12:11:52.418823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.rls import disable_rls, enable_rls


# revision identifiers, used by Alembic.
revision: str = '0a561fd73793'
down_revision: Union[str, Sequence[str], None] = 'db8f4db0e58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    disable_rls('user_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    enable_rls('user_roles')
    # ### end Alembic commands ###
