"""Sync UserMfaMethod

Revision ID: 261bdee314d7
Revises: 8d7e354b271c
Create Date: 2026-08-09 01:26:35.657217

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '261bdee314d7'
down_revision: str | Sequence[str] | None = '8d7e354b271c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_mfa_methods', sa.Column('encrypted_secret', sa.String(length=255), nullable=False))
    op.add_column('user_mfa_methods', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.drop_column('user_mfa_methods', 'secret')
    op.drop_column('user_mfa_methods', 'method_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_mfa_methods', sa.Column('method_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user_mfa_methods', sa.Column('secret', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('user_mfa_methods', 'provider_id')
    op.drop_column('user_mfa_methods', 'encrypted_secret')
    # ### end Alembic commands ###
