"""Phase 27: Add MFA TOTP fields

Revision ID: 332634d9dc20
Revises: 7558a909338a
Create Date: 2026-08-11 09:44:24.299993

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "332634d9dc20"
down_revision: str | Sequence[str] | None = "7558a909338a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_mfa_methods",
        sa.Column(
            "hashed_recovery_codes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "user_mfa_methods", sa.Column("failed_attempts", sa.Integer(), nullable=False)
    )
    op.add_column(
        "user_mfa_methods",
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_mfa_methods", "locked_until")
    op.drop_column("user_mfa_methods", "failed_attempts")
    op.drop_column("user_mfa_methods", "hashed_recovery_codes")
    # ### end Alembic commands ###
