"""Add Phase 8 Membership domain models

Revision ID: 45e716039e1c
Revises: 0a561fd73793
Create Date: 2026-08-09 13:12:50.913792

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "45e716039e1c"
down_revision: str | Sequence[str] | None = "0a561fd73793"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "membership_freezes",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_membership_freezes_tenant_id"),
    )
    op.create_index(
        op.f("ix_membership_freezes_tenant_id"),
        "membership_freezes",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "membership_periods",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_membership_periods_tenant_id"),
    )
    op.create_index(
        op.f("ix_membership_periods_tenant_id"),
        "membership_periods",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "membership_status_history",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("old_status", sa.String(), nullable=False),
        sa.Column("new_status", sa.String(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "id", name="uq_membership_status_history_tenant_id"
        ),
    )
    op.create_index(
        op.f("ix_membership_status_history_tenant_id"),
        "membership_status_history",
        ["tenant_id"],
        unique=False,
    )

    enable_rls("membership_freezes")
    enable_rls("membership_periods")
    enable_rls("membership_status_history")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    disable_rls("membership_status_history")
    disable_rls("membership_periods")
    disable_rls("membership_freezes")

    op.drop_index(
        op.f("ix_membership_status_history_tenant_id"),
        table_name="membership_status_history",
    )
    op.drop_table("membership_status_history")
    op.drop_index(
        op.f("ix_membership_periods_tenant_id"), table_name="membership_periods"
    )
    op.drop_table("membership_periods")
    op.drop_index(
        op.f("ix_membership_freezes_tenant_id"), table_name="membership_freezes"
    )
    op.drop_table("membership_freezes")
    # ### end Alembic commands ###
