"""add status to membership_renewals

Revision ID: 62afa7f4b3b1
Revises: ca8b3fd77206
Create Date: 2026-08-09 17:57:17.709344

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62afa7f4b3b1"
down_revision: str | Sequence[str] | None = "ca8b3fd77206"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "membership_renewals", sa.Column("status", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("membership_renewals", "status")
    # ### end Alembic commands ###
