"""Add operational MVP models

Revision ID: 67eca287af30
Revises: a1b2c3d4e5f6
Create Date: 2026-08-08 23:56:01.080745

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = '67eca287af30'
down_revision: str | Sequence[str] | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_events_event_id'), 'inbox_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_inbox_events_status'), 'inbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_inbox_events_tenant_id'), 'inbox_events', ['tenant_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_tenant_id'), 'notification_templates', ['tenant_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_table('report_definitions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_definitions_tenant_id'), 'report_definitions', ['tenant_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_deliveries_tenant_id'), 'notification_deliveries', ['tenant_id'], unique=False)
    op.create_table('report_runs',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_url', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['report_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_runs_tenant_id'), 'report_runs', ['tenant_id'], unique=False)
    
    enable_rls('inbox_events')
    enable_rls('notification_templates')
    enable_rls('outbox_events')
    enable_rls('report_definitions')
    enable_rls('notification_deliveries')
    enable_rls('report_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    disable_rls('report_runs')
    disable_rls('notification_deliveries')
    disable_rls('report_definitions')
    disable_rls('outbox_events')
    disable_rls('notification_templates')
    disable_rls('inbox_events')
    op.drop_index(op.f('ix_report_runs_tenant_id'), table_name='report_runs')
    op.drop_table('report_runs')
    op.drop_index(op.f('ix_notification_deliveries_tenant_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_report_definitions_tenant_id'), table_name='report_definitions')
    op.drop_table('report_definitions')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_notification_templates_tenant_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_inbox_events_tenant_id'), table_name='inbox_events')
    op.drop_index(op.f('ix_inbox_events_status'), table_name='inbox_events')
    op.drop_index(op.f('ix_inbox_events_event_id'), table_name='inbox_events')
    op.drop_table('inbox_events')
    # ### end Alembic commands ###
