"""composite_tenant_fks

Revision ID: 8d7e354b271c
Revises: 32bea30c0ed8
Create Date: 2026-08-09 00:40:50.840134

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d7e354b271c"
down_revision: str | Sequence[str] | None = "32bea30c0ed8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_access_attempts_tenant_id", "access_attempts", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_billing_accounts_tenant_id", "billing_accounts", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_checkins_tenant_id", "checkins", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_compliance_records_tenant_id", "compliance_records", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_consent_definitions_tenant_id", "consent_definitions", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_consent_records_tenant_id", "consent_records", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_consent_versions_tenant_id", "consent_versions", ["tenant_id", "id"]
    )
    op.create_unique_constraint("uq_devices_tenant_id", "devices", ["tenant_id", "id"])
    op.create_unique_constraint(
        "uq_entitlements_tenant_id", "entitlements", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_inbox_events_tenant_id", "inbox_events", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_invoice_items_tenant_id", "invoice_items", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_invoices_tenant_id", "invoices", ["tenant_id", "id"]
    )
    op.create_unique_constraint("uq_leads_tenant_id", "leads", ["tenant_id", "id"])
    op.create_unique_constraint(
        "uq_locations_tenant_id", "locations", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_member_notes_tenant_id", "member_notes", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_member_tags_tenant_id", "member_tags", ["tenant_id", "id"]
    )
    op.create_unique_constraint("uq_members_tenant_id", "members", ["tenant_id", "id"])
    op.create_unique_constraint(
        "uq_memberships_tenant_id", "memberships", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_notification_deliveries_tenant_id",
        "notification_deliveries",
        ["tenant_id", "id"],
    )
    op.create_unique_constraint(
        "uq_notification_templates_tenant_id",
        "notification_templates",
        ["tenant_id", "id"],
    )
    op.create_unique_constraint(
        "uq_offline_snapshots_tenant_id", "offline_snapshots", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_opportunities_tenant_id", "opportunities", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_outbox_events_tenant_id", "outbox_events", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_passport_configs_tenant_id", "passport_configs", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_payment_allocations_tenant_id", "payment_allocations", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_payments_tenant_id", "payments", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_plan_versions_tenant_id", "plan_versions", ["tenant_id", "id"]
    )
    op.create_unique_constraint("uq_plans_tenant_id", "plans", ["tenant_id", "id"])
    op.create_unique_constraint(
        "uq_report_definitions_tenant_id", "report_definitions", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_report_runs_tenant_id", "report_runs", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_retention_cockpit_tenant_id", "retention_cockpit", ["tenant_id", "id"]
    )
    op.create_unique_constraint(
        "uq_signing_keys_tenant_id", "signing_keys", ["tenant_id", "id"]
    )
    op.create_unique_constraint("uq_staff_tenant_id", "staff", ["tenant_id", "id"])
    op.create_unique_constraint("uq_tasks_tenant_id", "tasks", ["tenant_id", "id"])
    op.create_unique_constraint(
        "uq_user_roles_tenant_id", "user_roles", ["tenant_id", "id"]
    )
    op.drop_index(op.f("ix_access_attempts_device_id"), table_name="access_attempts")
    op.drop_index(op.f("ix_access_attempts_member_id"), table_name="access_attempts")
    op.drop_constraint(
        op.f("access_attempts_device_id_fkey"), "access_attempts", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("access_attempts_member_id_fkey"), "access_attempts", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "access_attempts",
        "devices",
        ["tenant_id", "device_id"],
        ["tenant_id", "id"],
    )
    op.create_foreign_key(
        None,
        "access_attempts",
        "members",
        ["tenant_id", "member_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("billing_accounts_member_id_fkey"), "billing_accounts", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "billing_accounts",
        "members",
        ["tenant_id", "member_id"],
        ["tenant_id", "id"],
    )
    op.drop_index(op.f("ix_checkins_device_id"), table_name="checkins")
    op.drop_index(op.f("ix_checkins_location_id"), table_name="checkins")
    op.drop_index(op.f("ix_checkins_member_id"), table_name="checkins")
    op.drop_constraint(op.f("checkins_device_id_fkey"), "checkins", type_="foreignkey")
    op.drop_constraint(
        op.f("checkins_location_id_fkey"), "checkins", type_="foreignkey"
    )
    op.drop_constraint(op.f("checkins_member_id_fkey"), "checkins", type_="foreignkey")
    op.create_foreign_key(
        None, "checkins", "members", ["tenant_id", "member_id"], ["tenant_id", "id"]
    )
    op.create_foreign_key(
        None, "checkins", "locations", ["tenant_id", "location_id"], ["tenant_id", "id"]
    )
    op.create_foreign_key(
        None, "checkins", "devices", ["tenant_id", "device_id"], ["tenant_id", "id"]
    )
    op.drop_constraint(
        op.f("consent_records_member_id_fkey"), "consent_records", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "consent_records",
        "members",
        ["tenant_id", "member_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("consent_versions_definition_id_fkey"),
        "consent_versions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "consent_versions",
        "consent_definitions",
        ["tenant_id", "definition_id"],
        ["tenant_id", "id"],
    )
    op.drop_index(op.f("ix_devices_location_id"), table_name="devices")
    op.drop_constraint(op.f("devices_location_id_fkey"), "devices", type_="foreignkey")
    op.create_foreign_key(
        None, "devices", "locations", ["tenant_id", "location_id"], ["tenant_id", "id"]
    )
    op.drop_constraint(
        op.f("entitlements_member_id_fkey"), "entitlements", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("entitlements_membership_id_fkey"), "entitlements", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "entitlements", "members", ["tenant_id", "member_id"], ["tenant_id", "id"]
    )
    op.create_foreign_key(
        None,
        "entitlements",
        "memberships",
        ["tenant_id", "membership_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("invoice_items_invoice_id_fkey"), "invoice_items", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "invoice_items",
        "invoices",
        ["tenant_id", "invoice_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("invoices_billing_account_id_fkey"), "invoices", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "invoices",
        "billing_accounts",
        ["tenant_id", "billing_account_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("member_notes_member_id_fkey"), "member_notes", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "member_notes", "members", ["tenant_id", "member_id"], ["tenant_id", "id"]
    )
    op.drop_constraint(
        op.f("member_tags_member_id_fkey"), "member_tags", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "member_tags", "members", ["tenant_id", "member_id"], ["tenant_id", "id"]
    )
    op.drop_constraint(
        op.f("memberships_member_id_fkey"), "memberships", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("memberships_plan_version_id_fkey"), "memberships", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "memberships",
        "plan_versions",
        ["tenant_id", "plan_version_id"],
        ["tenant_id", "id"],
    )
    op.create_foreign_key(
        None, "memberships", "members", ["tenant_id", "member_id"], ["tenant_id", "id"]
    )
    op.drop_constraint(
        op.f("notification_deliveries_template_id_fkey"),
        "notification_deliveries",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "notification_deliveries",
        "notification_templates",
        ["tenant_id", "template_id"],
        ["tenant_id", "id"],
    )
    op.drop_index(
        op.f("ix_offline_snapshots_device_id"), table_name="offline_snapshots"
    )
    op.drop_constraint(
        op.f("offline_snapshots_device_id_fkey"),
        "offline_snapshots",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "offline_snapshots",
        "devices",
        ["tenant_id", "device_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("opportunities_lead_id_fkey"), "opportunities", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("opportunities_member_id_fkey"), "opportunities", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "opportunities", "leads", ["tenant_id", "lead_id"], ["tenant_id", "id"]
    )
    op.create_foreign_key(
        None,
        "opportunities",
        "members",
        ["tenant_id", "member_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("payment_allocations_invoice_id_fkey"),
        "payment_allocations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("payment_allocations_payment_id_fkey"),
        "payment_allocations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "payment_allocations",
        "invoices",
        ["tenant_id", "invoice_id"],
        ["tenant_id", "id"],
    )
    op.create_foreign_key(
        None,
        "payment_allocations",
        "payments",
        ["tenant_id", "payment_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("payments_billing_account_id_fkey"), "payments", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "payments",
        "billing_accounts",
        ["tenant_id", "billing_account_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("plan_versions_plan_id_fkey"), "plan_versions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "plan_versions", "plans", ["tenant_id", "plan_id"], ["tenant_id", "id"]
    )
    op.drop_constraint(
        op.f("report_runs_definition_id_fkey"), "report_runs", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "report_runs",
        "report_definitions",
        ["tenant_id", "definition_id"],
        ["tenant_id", "id"],
    )
    op.drop_constraint(
        op.f("retention_cockpit_member_id_fkey"),
        "retention_cockpit",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "retention_cockpit",
        "members",
        ["tenant_id", "member_id"],
        ["tenant_id", "id"],
    )
    op.alter_column(
        "signing_keys",
        "key_material",
        existing_type=sa.TEXT(),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("staff_location_id_fkey"), "staff", type_="foreignkey")
    op.create_foreign_key(
        None, "staff", "locations", ["tenant_id", "location_id"], ["tenant_id", "id"]
    )
    op.drop_constraint(op.f("tasks_member_id_fkey"), "tasks", type_="foreignkey")
    op.drop_constraint(op.f("tasks_lead_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "members", ["tenant_id", "member_id"], ["tenant_id", "id"]
    )
    op.create_foreign_key(
        None, "tasks", "leads", ["tenant_id", "lead_id"], ["tenant_id", "id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "tasks", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "staff", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "retention_cockpit", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "report_runs", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "plan_versions", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "payments", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "payment_allocations", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "payment_allocations", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "opportunities", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "opportunities", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "offline_snapshots", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "notification_deliveries", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "memberships", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "memberships", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "member_tags", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "member_notes", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "invoices", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "invoice_items", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "entitlements", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "entitlements", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "devices", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "consent_versions", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "consent_records", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "checkins", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "checkins", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "checkins", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "billing_accounts", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "access_attempts", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "access_attempts", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint("uq_user_roles_tenant_id", "user_roles", type_="unique")
    op.create_foreign_key(
        op.f("tasks_lead_id_fkey"), "tasks", "leads", ["lead_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("tasks_member_id_fkey"), "tasks", "members", ["member_id"], ["id"]
    )
    op.drop_constraint("uq_tasks_tenant_id", "tasks", type_="unique")
    op.create_foreign_key(
        op.f("staff_location_id_fkey"), "staff", "locations", ["location_id"], ["id"]
    )
    op.drop_constraint("uq_staff_tenant_id", "staff", type_="unique")
    op.drop_constraint("uq_signing_keys_tenant_id", "signing_keys", type_="unique")
    op.alter_column(
        "signing_keys",
        "key_material",
        existing_type=sa.String(length=200),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("retention_cockpit_member_id_fkey"),
        "retention_cockpit",
        "members",
        ["member_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_retention_cockpit_tenant_id", "retention_cockpit", type_="unique"
    )
    op.create_foreign_key(
        op.f("report_runs_definition_id_fkey"),
        "report_runs",
        "report_definitions",
        ["definition_id"],
        ["id"],
    )
    op.drop_constraint("uq_report_runs_tenant_id", "report_runs", type_="unique")
    op.drop_constraint(
        "uq_report_definitions_tenant_id", "report_definitions", type_="unique"
    )
    op.drop_constraint("uq_plans_tenant_id", "plans", type_="unique")
    op.create_foreign_key(
        op.f("plan_versions_plan_id_fkey"),
        "plan_versions",
        "plans",
        ["plan_id"],
        ["id"],
    )
    op.drop_constraint("uq_plan_versions_tenant_id", "plan_versions", type_="unique")
    op.create_foreign_key(
        op.f("payments_billing_account_id_fkey"),
        "payments",
        "billing_accounts",
        ["billing_account_id"],
        ["id"],
    )
    op.drop_constraint("uq_payments_tenant_id", "payments", type_="unique")
    op.create_foreign_key(
        op.f("payment_allocations_payment_id_fkey"),
        "payment_allocations",
        "payments",
        ["payment_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("payment_allocations_invoice_id_fkey"),
        "payment_allocations",
        "invoices",
        ["invoice_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_payment_allocations_tenant_id", "payment_allocations", type_="unique"
    )
    op.drop_constraint(
        "uq_passport_configs_tenant_id", "passport_configs", type_="unique"
    )
    op.drop_constraint("uq_outbox_events_tenant_id", "outbox_events", type_="unique")
    op.create_foreign_key(
        op.f("opportunities_member_id_fkey"),
        "opportunities",
        "members",
        ["member_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("opportunities_lead_id_fkey"),
        "opportunities",
        "leads",
        ["lead_id"],
        ["id"],
    )
    op.drop_constraint("uq_opportunities_tenant_id", "opportunities", type_="unique")
    op.create_foreign_key(
        op.f("offline_snapshots_device_id_fkey"),
        "offline_snapshots",
        "devices",
        ["device_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_offline_snapshots_tenant_id", "offline_snapshots", type_="unique"
    )
    op.create_index(
        op.f("ix_offline_snapshots_device_id"),
        "offline_snapshots",
        ["device_id"],
        unique=False,
    )
    op.drop_constraint(
        "uq_notification_templates_tenant_id", "notification_templates", type_="unique"
    )
    op.create_foreign_key(
        op.f("notification_deliveries_template_id_fkey"),
        "notification_deliveries",
        "notification_templates",
        ["template_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_notification_deliveries_tenant_id",
        "notification_deliveries",
        type_="unique",
    )
    op.create_foreign_key(
        op.f("memberships_plan_version_id_fkey"),
        "memberships",
        "plan_versions",
        ["plan_version_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("memberships_member_id_fkey"),
        "memberships",
        "members",
        ["member_id"],
        ["id"],
    )
    op.drop_constraint("uq_memberships_tenant_id", "memberships", type_="unique")
    op.drop_constraint("uq_members_tenant_id", "members", type_="unique")
    op.create_foreign_key(
        op.f("member_tags_member_id_fkey"),
        "member_tags",
        "members",
        ["member_id"],
        ["id"],
    )
    op.drop_constraint("uq_member_tags_tenant_id", "member_tags", type_="unique")
    op.create_foreign_key(
        op.f("member_notes_member_id_fkey"),
        "member_notes",
        "members",
        ["member_id"],
        ["id"],
    )
    op.drop_constraint("uq_member_notes_tenant_id", "member_notes", type_="unique")
    op.drop_constraint("uq_locations_tenant_id", "locations", type_="unique")
    op.drop_constraint("uq_leads_tenant_id", "leads", type_="unique")
    op.create_foreign_key(
        op.f("invoices_billing_account_id_fkey"),
        "invoices",
        "billing_accounts",
        ["billing_account_id"],
        ["id"],
    )
    op.drop_constraint("uq_invoices_tenant_id", "invoices", type_="unique")
    op.create_foreign_key(
        op.f("invoice_items_invoice_id_fkey"),
        "invoice_items",
        "invoices",
        ["invoice_id"],
        ["id"],
    )
    op.drop_constraint("uq_invoice_items_tenant_id", "invoice_items", type_="unique")
    op.drop_constraint("uq_inbox_events_tenant_id", "inbox_events", type_="unique")
    op.create_foreign_key(
        op.f("entitlements_membership_id_fkey"),
        "entitlements",
        "memberships",
        ["membership_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("entitlements_member_id_fkey"),
        "entitlements",
        "members",
        ["member_id"],
        ["id"],
    )
    op.drop_constraint("uq_entitlements_tenant_id", "entitlements", type_="unique")
    op.create_foreign_key(
        op.f("devices_location_id_fkey"),
        "devices",
        "locations",
        ["location_id"],
        ["id"],
    )
    op.drop_constraint("uq_devices_tenant_id", "devices", type_="unique")
    op.create_index(
        op.f("ix_devices_location_id"), "devices", ["location_id"], unique=False
    )
    op.create_foreign_key(
        op.f("consent_versions_definition_id_fkey"),
        "consent_versions",
        "consent_definitions",
        ["definition_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_consent_versions_tenant_id", "consent_versions", type_="unique"
    )
    op.create_foreign_key(
        op.f("consent_records_member_id_fkey"),
        "consent_records",
        "members",
        ["member_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_consent_records_tenant_id", "consent_records", type_="unique"
    )
    op.drop_constraint(
        "uq_consent_definitions_tenant_id", "consent_definitions", type_="unique"
    )
    op.drop_constraint(
        "uq_compliance_records_tenant_id", "compliance_records", type_="unique"
    )
    op.create_foreign_key(
        op.f("checkins_member_id_fkey"), "checkins", "members", ["member_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("checkins_location_id_fkey"),
        "checkins",
        "locations",
        ["location_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("checkins_device_id_fkey"), "checkins", "devices", ["device_id"], ["id"]
    )
    op.drop_constraint("uq_checkins_tenant_id", "checkins", type_="unique")
    op.create_index(
        op.f("ix_checkins_member_id"), "checkins", ["member_id"], unique=False
    )
    op.create_index(
        op.f("ix_checkins_location_id"), "checkins", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_checkins_device_id"), "checkins", ["device_id"], unique=False
    )
    op.create_foreign_key(
        op.f("billing_accounts_member_id_fkey"),
        "billing_accounts",
        "members",
        ["member_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_billing_accounts_tenant_id", "billing_accounts", type_="unique"
    )
    op.create_foreign_key(
        op.f("access_attempts_member_id_fkey"),
        "access_attempts",
        "members",
        ["member_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("access_attempts_device_id_fkey"),
        "access_attempts",
        "devices",
        ["device_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_access_attempts_tenant_id", "access_attempts", type_="unique"
    )
    op.create_index(
        op.f("ix_access_attempts_member_id"),
        "access_attempts",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_attempts_device_id"),
        "access_attempts",
        ["device_id"],
        unique=False,
    )
    # ### end Alembic commands ###
