"""Phase 27: Add device auth models

Revision ID: 96b95a7a1de8
Revises: 6590aca081d6
Create Date: 2026-08-11 01:09:09.679113

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96b95a7a1de8"
down_revision: str | Sequence[str] | None = "6590aca081d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_sessions",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "device_id"],
            ["devices.tenant_id", "devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_device_sessions_tenant_id"),
    )
    op.create_index(
        op.f("ix_device_sessions_tenant_id"),
        "device_sessions",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_sessions_token_hash"),
        "device_sessions",
        ["token_hash"],
        unique=True,
    )
    op.add_column(
        "devices", sa.Column("api_key_hash", sa.String(length=255), nullable=True)
    )
    op.add_column("devices", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "is_active")
    op.drop_column("devices", "api_key_hash")
    op.drop_index(op.f("ix_device_sessions_token_hash"), table_name="device_sessions")
    op.drop_index(op.f("ix_device_sessions_tenant_id"), table_name="device_sessions")
    op.drop_table("device_sessions")
    # ### end Alembic commands ###
