"""add_chk_user_roles_tenant_or_org

Revision ID: b3655ea622c4
Revises: 9d407d31b6cb
Create Date: 2026-08-09 14:45:45.471900

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3655ea622c4"
down_revision: str | Sequence[str] | None = "9d407d31b6cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "chk_user_roles_tenant_or_org",
        "user_roles",
        "(tenant_id IS NULL) OR (organization_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chk_user_roles_tenant_or_org", "user_roles", type_="check")
    # ### end Alembic commands ###
