"""Add entitlement models

Revision ID: b3e2852df357
Revises: 62afa7f4b3b1
Create Date: 2026-08-09 18:30:51.798299

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3e2852df357'
down_revision: str | Sequence[str] | None = '62afa7f4b3b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitlement_definitions',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('COUNT', 'BOOLEAN', name='entitlementtype'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_entitlement_definitions_tenant_id')
    )
    op.create_index('ix_entitlement_def_tenant_code', 'entitlement_definitions', ['tenant_id', 'code'], unique=True)
    op.create_index(op.f('ix_entitlement_definitions_tenant_id'), 'entitlement_definitions', ['tenant_id'], unique=False)
    op.create_table('entitlement_wallets',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('entitlement_id', sa.Uuid(), nullable=False),
    sa.Column('allocated', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'entitlement_id'], ['entitlement_definitions.tenant_id', 'entitlement_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'member_id'], ['members.tenant_id', 'members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_entitlement_wallets_tenant_id')
    )
    op.create_index('ix_entit_wallets_tenant_memb_entit', 'entitlement_wallets', ['tenant_id', 'member_id', 'entitlement_id'], unique=True)
    op.create_index(op.f('ix_entitlement_wallets_tenant_id'), 'entitlement_wallets', ['tenant_id'], unique=False)
    op.create_table('plan_entitlements',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('entitlement_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'entitlement_id'], ['entitlement_definitions.tenant_id', 'entitlement_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'plan_id'], ['plans.tenant_id', 'plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_plan_entitlements_tenant_id')
    )
    op.create_index('ix_plan_entit_tenant_plan_entit', 'plan_entitlements', ['tenant_id', 'plan_id', 'entitlement_id'], unique=True)
    op.create_index(op.f('ix_plan_entitlements_tenant_id'), 'plan_entitlements', ['tenant_id'], unique=False)
    op.create_table('entitlement_transactions',
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'wallet_id'], ['entitlement_wallets.tenant_id', 'entitlement_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_entitlement_transactions_tenant_id')
    )
    op.create_index('ix_entit_tx_tenant_idem_key', 'entitlement_transactions', ['tenant_id', 'idempotency_key'], unique=True)
    op.create_index(op.f('ix_entitlement_transactions_tenant_id'), 'entitlement_transactions', ['tenant_id'], unique=False)
    op.create_table('membership_entitlements',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('entitlement_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'entitlement_id'], ['entitlement_definitions.tenant_id', 'entitlement_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'membership_id'], ['memberships.tenant_id', 'memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_membership_entitlements_tenant_id')
    )
    op.create_index('ix_memb_entit_tenant_memb_entit', 'membership_entitlements', ['tenant_id', 'membership_id', 'entitlement_id'], unique=True)
    op.create_index(op.f('ix_membership_entitlements_tenant_id'), 'membership_entitlements', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_entitlements_tenant_id'), table_name='membership_entitlements')
    op.drop_index('ix_memb_entit_tenant_memb_entit', table_name='membership_entitlements')
    op.drop_table('membership_entitlements')
    op.drop_index(op.f('ix_entitlement_transactions_tenant_id'), table_name='entitlement_transactions')
    op.drop_index('ix_entit_tx_tenant_idem_key', table_name='entitlement_transactions')
    op.drop_table('entitlement_transactions')
    op.drop_index(op.f('ix_plan_entitlements_tenant_id'), table_name='plan_entitlements')
    op.drop_index('ix_plan_entit_tenant_plan_entit', table_name='plan_entitlements')
    op.drop_table('plan_entitlements')
    op.drop_index(op.f('ix_entitlement_wallets_tenant_id'), table_name='entitlement_wallets')
    op.drop_index('ix_entit_wallets_tenant_memb_entit', table_name='entitlement_wallets')
    op.drop_table('entitlement_wallets')
    op.drop_index(op.f('ix_entitlement_definitions_tenant_id'), table_name='entitlement_definitions')
    op.drop_index('ix_entitlement_def_tenant_code', table_name='entitlement_definitions')
    op.drop_table('entitlement_definitions')
    # ### end Alembic commands ###
