"""add membership cancellation and renewal models

Revision ID: b5994ffbd643
Revises: b3655ea622c4
Create Date: 2026-08-09 14:51:19.056699

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "b5994ffbd643"
down_revision: str | Sequence[str] | None = "b3655ea622c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "membership_cancellations",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "id", name="uq_membership_cancellations_tenant_id"
        ),
    )
    op.create_index(
        op.f("ix_membership_cancellations_tenant_id"),
        "membership_cancellations",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "membership_renewals",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("next_plan_version_id", sa.Uuid(), nullable=True),
        sa.Column("renewal_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_snapshot", sa.Integer(), nullable=True),
        sa.Column("terms_snapshot", sa.String(), nullable=True),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["memberships.tenant_id", "memberships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "next_plan_version_id"],
            ["plan_versions.tenant_id", "plan_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_membership_renewals_tenant_id"),
    )
    op.create_index(
        op.f("ix_membership_renewals_tenant_id"),
        "membership_renewals",
        ["tenant_id"],
        unique=False,
    )
    op.add_column(
        "memberships", sa.Column("price_snapshot", sa.Integer(), nullable=True)
    )
    op.add_column(
        "memberships", sa.Column("terms_snapshot", sa.String(), nullable=True)
    )
    op.add_column(
        "plan_versions", sa.Column("is_published", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "plan_versions",
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.execute("UPDATE plan_versions SET is_published = false")
    op.alter_column("plan_versions", "is_published", nullable=False)

    enable_rls("membership_cancellations")
    enable_rls("membership_renewals")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    disable_rls("membership_renewals")
    disable_rls("membership_cancellations")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan_versions", "published_at")
    op.drop_column("plan_versions", "is_published")
    op.drop_column("memberships", "terms_snapshot")
    op.drop_column("memberships", "price_snapshot")
    op.drop_index(
        op.f("ix_membership_renewals_tenant_id"), table_name="membership_renewals"
    )
    op.drop_table("membership_renewals")
    op.drop_index(
        op.f("ix_membership_cancellations_tenant_id"),
        table_name="membership_cancellations",
    )
    op.drop_table("membership_cancellations")
    # ### end Alembic commands ###
