"""Add terms JSON fields

Revision ID: bc4033d03939
Revises: e0675d75481a
Create Date: 2026-08-09 17:31:32.929948

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc4033d03939'
down_revision: str | Sequence[str] | None = 'e0675d75481a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('membership_renewals', 'terms_snapshot',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="terms_snapshot::json")
    op.alter_column('memberships', 'terms_snapshot',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="terms_snapshot::json")
    op.add_column('plan_versions', sa.Column('terms', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_versions', 'terms')
    op.alter_column('memberships', 'terms_snapshot',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('membership_renewals', 'terms_snapshot',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
