"""composite_tenant_fks

Revision ID: c52bd2239c3d
Revises: 32bea30c0ed8
Create Date: 2026-08-09 00:08:41.170152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52bd2239c3d'
down_revision: Union[str, Sequence[str], None] = '32bea30c0ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_attempts_device_id'), table_name='access_attempts')
    op.drop_index(op.f('ix_access_attempts_member_id'), table_name='access_attempts')
    op.create_unique_constraint('uq_access_attempts_tenant_id', 'access_attempts', ['tenant_id', 'id'])
    op.drop_constraint(op.f('access_attempts_device_id_fkey'), 'access_attempts', type_='foreignkey')
    op.drop_constraint(op.f('access_attempts_member_id_fkey'), 'access_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'access_attempts', 'devices', ['tenant_id', 'device_id'], ['tenant_id', 'id'])
    op.create_foreign_key(None, 'access_attempts', 'members', ['tenant_id', 'member_id'], ['tenant_id', 'id'])
    op.create_unique_constraint('uq_billing_accounts_tenant_id', 'billing_accounts', ['tenant_id', 'id'])
    op.drop_constraint(op.f('billing_accounts_member_id_fkey'), 'billing_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'billing_accounts', 'members', ['tenant_id', 'member_id'], ['tenant_id', 'id'])
    op.drop_index(op.f('ix_checkins_device_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_location_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_member_id'), table_name='checkins')
    op.create_unique_constraint('uq_checkins_tenant_id', 'checkins', ['tenant_id', 'id'])
    op.drop_constraint(op.f('checkins_device_id_fkey'), 'checkins', type_='foreignkey')
    op.drop_constraint(op.f('checkins_member_id_fkey'), 'checkins', type_='foreignkey')
    op.drop_constraint(op.f('checkins_location_id_fkey'), 'checkins', type_='foreignkey')
    op.create_foreign_key(None, 'checkins', 'locations', ['tenant_id', 'location_id'], ['tenant_id', 'id'])
    op.create_foreign_key(None, 'checkins', 'members', ['tenant_id', 'member_id'], ['tenant_id', 'id'])
    op.create_foreign_key(None, 'checkins', 'devices', ['tenant_id', 'device_id'], ['tenant_id', 'id'])
    op.create_unique_constraint('uq_compliance_records_tenant_id', 'compliance_records', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_consent_definitions_tenant_id', 'consent_definitions', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_consent_records_tenant_id', 'consent_records', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_consent_versions_tenant_id', 'consent_versions', ['tenant_id', 'id'])
    op.drop_index(op.f('ix_devices_location_id'), table_name='devices')
    op.create_unique_constraint('uq_devices_tenant_id', 'devices', ['tenant_id', 'id'])
    op.drop_constraint(op.f('devices_location_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'locations', ['tenant_id', 'location_id'], ['tenant_id', 'id'])
    op.create_unique_constraint('uq_entitlements_tenant_id', 'entitlements', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_inbox_events_tenant_id', 'inbox_events', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_invoice_items_tenant_id', 'invoice_items', ['tenant_id', 'id'])
    op.drop_constraint(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoices', ['tenant_id', 'invoice_id'], ['tenant_id', 'id'])
    op.create_unique_constraint('uq_invoices_tenant_id', 'invoices', ['tenant_id', 'id'])
    op.drop_constraint(op.f('invoices_billing_account_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'billing_accounts', ['tenant_id', 'billing_account_id'], ['tenant_id', 'id'])
    op.create_unique_constraint('uq_leads_tenant_id', 'leads', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_locations_tenant_id', 'locations', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_member_notes_tenant_id', 'member_notes', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_member_tags_tenant_id', 'member_tags', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_members_tenant_id', 'members', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_memberships_tenant_id', 'memberships', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_notification_deliveries_tenant_id', 'notification_deliveries', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_notification_templates_tenant_id', 'notification_templates', ['tenant_id', 'id'])
    op.drop_index(op.f('ix_offline_snapshots_device_id'), table_name='offline_snapshots')
    op.create_unique_constraint('uq_offline_snapshots_tenant_id', 'offline_snapshots', ['tenant_id', 'id'])
    op.drop_constraint(op.f('offline_snapshots_device_id_fkey'), 'offline_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'offline_snapshots', 'devices', ['tenant_id', 'device_id'], ['tenant_id', 'id'])
    op.create_unique_constraint('uq_opportunities_tenant_id', 'opportunities', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_outbox_events_tenant_id', 'outbox_events', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_passport_configs_tenant_id', 'passport_configs', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_payment_allocations_tenant_id', 'payment_allocations', ['tenant_id', 'id'])
    op.drop_constraint(op.f('payment_allocations_payment_id_fkey'), 'payment_allocations', type_='foreignkey')
    op.drop_constraint(op.f('payment_allocations_invoice_id_fkey'), 'payment_allocations', type_='foreignkey')
    op.create_foreign_key(None, 'payment_allocations', 'invoices', ['tenant_id', 'invoice_id'], ['tenant_id', 'id'])
    op.create_foreign_key(None, 'payment_allocations', 'payments', ['tenant_id', 'payment_id'], ['tenant_id', 'id'])
    op.create_unique_constraint('uq_payments_tenant_id', 'payments', ['tenant_id', 'id'])
    op.drop_constraint(op.f('payments_billing_account_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'billing_accounts', ['tenant_id', 'billing_account_id'], ['tenant_id', 'id'])
    op.create_unique_constraint('uq_plan_versions_tenant_id', 'plan_versions', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_plans_tenant_id', 'plans', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_report_definitions_tenant_id', 'report_definitions', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_report_runs_tenant_id', 'report_runs', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_retention_cockpit_tenant_id', 'retention_cockpit', ['tenant_id', 'id'])
    op.alter_column('signing_keys', 'key_material',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.create_unique_constraint('uq_signing_keys_tenant_id', 'signing_keys', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_staff_tenant_id', 'staff', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_tasks_tenant_id', 'tasks', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_user_roles_tenant_id', 'user_roles', ['tenant_id', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_roles_tenant_id', 'user_roles', type_='unique')
    op.drop_constraint('uq_tasks_tenant_id', 'tasks', type_='unique')
    op.drop_constraint('uq_staff_tenant_id', 'staff', type_='unique')
    op.drop_constraint('uq_signing_keys_tenant_id', 'signing_keys', type_='unique')
    op.alter_column('signing_keys', 'key_material',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_retention_cockpit_tenant_id', 'retention_cockpit', type_='unique')
    op.drop_constraint('uq_report_runs_tenant_id', 'report_runs', type_='unique')
    op.drop_constraint('uq_report_definitions_tenant_id', 'report_definitions', type_='unique')
    op.drop_constraint('uq_plans_tenant_id', 'plans', type_='unique')
    op.drop_constraint('uq_plan_versions_tenant_id', 'plan_versions', type_='unique')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_billing_account_id_fkey'), 'payments', 'billing_accounts', ['billing_account_id'], ['id'])
    op.drop_constraint('uq_payments_tenant_id', 'payments', type_='unique')
    op.drop_constraint(None, 'payment_allocations', type_='foreignkey')
    op.drop_constraint(None, 'payment_allocations', type_='foreignkey')
    op.create_foreign_key(op.f('payment_allocations_invoice_id_fkey'), 'payment_allocations', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key(op.f('payment_allocations_payment_id_fkey'), 'payment_allocations', 'payments', ['payment_id'], ['id'])
    op.drop_constraint('uq_payment_allocations_tenant_id', 'payment_allocations', type_='unique')
    op.drop_constraint('uq_passport_configs_tenant_id', 'passport_configs', type_='unique')
    op.drop_constraint('uq_outbox_events_tenant_id', 'outbox_events', type_='unique')
    op.drop_constraint('uq_opportunities_tenant_id', 'opportunities', type_='unique')
    op.drop_constraint(None, 'offline_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('offline_snapshots_device_id_fkey'), 'offline_snapshots', 'devices', ['device_id'], ['id'])
    op.drop_constraint('uq_offline_snapshots_tenant_id', 'offline_snapshots', type_='unique')
    op.create_index(op.f('ix_offline_snapshots_device_id'), 'offline_snapshots', ['device_id'], unique=False)
    op.drop_constraint('uq_notification_templates_tenant_id', 'notification_templates', type_='unique')
    op.drop_constraint('uq_notification_deliveries_tenant_id', 'notification_deliveries', type_='unique')
    op.drop_constraint('uq_memberships_tenant_id', 'memberships', type_='unique')
    op.drop_constraint('uq_members_tenant_id', 'members', type_='unique')
    op.drop_constraint('uq_member_tags_tenant_id', 'member_tags', type_='unique')
    op.drop_constraint('uq_member_notes_tenant_id', 'member_notes', type_='unique')
    op.drop_constraint('uq_locations_tenant_id', 'locations', type_='unique')
    op.drop_constraint('uq_leads_tenant_id', 'leads', type_='unique')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_billing_account_id_fkey'), 'invoices', 'billing_accounts', ['billing_account_id'], ['id'])
    op.drop_constraint('uq_invoices_tenant_id', 'invoices', type_='unique')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.drop_constraint('uq_invoice_items_tenant_id', 'invoice_items', type_='unique')
    op.drop_constraint('uq_inbox_events_tenant_id', 'inbox_events', type_='unique')
    op.drop_constraint('uq_entitlements_tenant_id', 'entitlements', type_='unique')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_location_id_fkey'), 'devices', 'locations', ['location_id'], ['id'])
    op.drop_constraint('uq_devices_tenant_id', 'devices', type_='unique')
    op.create_index(op.f('ix_devices_location_id'), 'devices', ['location_id'], unique=False)
    op.drop_constraint('uq_consent_versions_tenant_id', 'consent_versions', type_='unique')
    op.drop_constraint('uq_consent_records_tenant_id', 'consent_records', type_='unique')
    op.drop_constraint('uq_consent_definitions_tenant_id', 'consent_definitions', type_='unique')
    op.drop_constraint('uq_compliance_records_tenant_id', 'compliance_records', type_='unique')
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.create_foreign_key(op.f('checkins_location_id_fkey'), 'checkins', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('checkins_member_id_fkey'), 'checkins', 'members', ['member_id'], ['id'])
    op.create_foreign_key(op.f('checkins_device_id_fkey'), 'checkins', 'devices', ['device_id'], ['id'])
    op.drop_constraint('uq_checkins_tenant_id', 'checkins', type_='unique')
    op.create_index(op.f('ix_checkins_member_id'), 'checkins', ['member_id'], unique=False)
    op.create_index(op.f('ix_checkins_location_id'), 'checkins', ['location_id'], unique=False)
    op.create_index(op.f('ix_checkins_device_id'), 'checkins', ['device_id'], unique=False)
    op.drop_constraint(None, 'billing_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('billing_accounts_member_id_fkey'), 'billing_accounts', 'members', ['member_id'], ['id'])
    op.drop_constraint('uq_billing_accounts_tenant_id', 'billing_accounts', type_='unique')
    op.drop_constraint(None, 'access_attempts', type_='foreignkey')
    op.drop_constraint(None, 'access_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('access_attempts_member_id_fkey'), 'access_attempts', 'members', ['member_id'], ['id'])
    op.create_foreign_key(op.f('access_attempts_device_id_fkey'), 'access_attempts', 'devices', ['device_id'], ['id'])
    op.drop_constraint('uq_access_attempts_tenant_id', 'access_attempts', type_='unique')
    op.create_index(op.f('ix_access_attempts_member_id'), 'access_attempts', ['member_id'], unique=False)
    op.create_index(op.f('ix_access_attempts_device_id'), 'access_attempts', ['device_id'], unique=False)
    # ### end Alembic commands ###
