"""Add Phase 8 Membership domain models

Revision ID: db8f4db0e58d
Revises: 261bdee314d7
Create Date: 2026-08-09 01:53:05.872486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8f4db0e58d'
down_revision: Union[str, Sequence[str], None] = '261bdee314d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_freezes',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'membership_id'], ['memberships.tenant_id', 'memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_membership_freezes_tenant_id')
    )
    op.create_index(op.f('ix_membership_freezes_tenant_id'), 'membership_freezes', ['tenant_id'], unique=False)
    op.create_table('status_history',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'membership_id'], ['memberships.tenant_id', 'memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_status_history_tenant_id')
    )
    op.create_index(op.f('ix_status_history_tenant_id'), 'status_history', ['tenant_id'], unique=False)
    op.create_table('subscription_periods',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'membership_id'], ['memberships.tenant_id', 'memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_subscription_periods_tenant_id')
    )
    op.create_index(op.f('ix_subscription_periods_tenant_id'), 'subscription_periods', ['tenant_id'], unique=False)
    op.add_column('user_roles', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.alter_column('user_roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_user_roles_tenant_id'), 'user_roles', type_='unique')
    op.create_index(op.f('ix_user_roles_organization_id'), 'user_roles', ['organization_id'], unique=False)
    op.create_foreign_key('fk_user_roles_tenants', 'user_roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_roles_organizations', 'user_roles', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_roles_organizations', 'user_roles', type_='foreignkey')
    op.drop_constraint('fk_user_roles_tenants', 'user_roles', type_='foreignkey')
    op.drop_index(op.f('ix_user_roles_organization_id'), table_name='user_roles')
    op.create_unique_constraint(op.f('uq_user_roles_tenant_id'), 'user_roles', ['tenant_id', 'id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('user_roles', 'organization_id')
    op.drop_index(op.f('ix_subscription_periods_tenant_id'), table_name='subscription_periods')
    op.drop_table('subscription_periods')
    op.drop_index(op.f('ix_status_history_tenant_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_membership_freezes_tenant_id'), table_name='membership_freezes')
    op.drop_table('membership_freezes')
    # ### end Alembic commands ###
