"""Add Phase 8 fixes

Revision ID: e0675d75481a
Revises: b5994ffbd643
Create Date: 2026-08-09 15:38:49.978739

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0675d75481a"
down_revision: str | Sequence[str] | None = "b5994ffbd643"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "membership_freezes", sa.Column("previous_status", sa.String(), nullable=True)
    )
    op.create_index(
        "ix_membership_freezes_active",
        "membership_freezes",
        ["tenant_id", "membership_id"],
        unique=True,
        postgresql_where=sa.text("actual_end_date IS NULL"),
    )
    op.add_column(
        "membership_renewals",
        sa.Column("price_snapshot_currency", sa.String(length=3), nullable=True),
    )
    op.add_column(
        "memberships",
        sa.Column(
            "scheduled_cancellation_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "memberships",
        sa.Column("price_snapshot_currency", sa.String(length=3), nullable=True),
    )
    op.add_column(
        "plan_versions", sa.Column("currency", sa.String(length=3), nullable=True)
    )

    # Backfill
    op.execute("UPDATE plan_versions SET currency = 'TRY' WHERE currency IS NULL")

    # Contract
    op.alter_column("plan_versions", "currency", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan_versions", "currency")
    op.drop_column("memberships", "price_snapshot_currency")
    op.drop_column("memberships", "scheduled_cancellation_at")
    op.drop_column("membership_renewals", "price_snapshot_currency")
    op.drop_index(
        "ix_membership_freezes_active",
        table_name="membership_freezes",
        postgresql_where=sa.text("actual_end_date IS NULL"),
    )
    op.drop_column("membership_freezes", "previous_status")
    # ### end Alembic commands ###
