"""sync wave3 schema drift

Revision ID: x8b9c0d1e2f3
Revises: x7a8b9c0d1e2
Create Date: 2026-08-15 09:49:53.695199

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "x8b9c0d1e2f3"
down_revision: str | Sequence[str] | None = "x7a8b9c0d1e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_data_import_batches_tenant_id"),
        "data_import_batches",
        ["tenant_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_data_import_batches_tenant_id", "data_import_batches", ["tenant_id", "id"]
    )
    op.drop_constraint(
        op.f("data_import_batches_tenant_id_fkey"),
        "data_import_batches",
        type_="foreignkey",
    )
    op.create_index(
        op.f("ix_data_import_rows_batch_id"),
        "data_import_rows",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_import_rows_tenant_id"),
        "data_import_rows",
        ["tenant_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_data_import_rows_tenant_id", "data_import_rows", ["tenant_id", "id"]
    )
    op.create_index(
        op.f("ix_dunning_policies_tenant_id"),
        "dunning_policies",
        ["tenant_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_dunning_policies_tenant_id", "dunning_policies", ["tenant_id", "id"]
    )
    op.drop_constraint(
        op.f("dunning_policies_tenant_id_fkey"), "dunning_policies", type_="foreignkey"
    )
    op.create_index(
        op.f("ix_payment_attempts_billing_account_id"),
        "payment_attempts",
        ["billing_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_attempts_invoice_id"),
        "payment_attempts",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_attempts_tenant_id"),
        "payment_attempts",
        ["tenant_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_payment_attempts_tenant_id", "payment_attempts", ["tenant_id", "id"]
    )
    op.create_index(
        op.f("ix_tenant_onboardings_tenant_id"),
        "tenant_onboardings",
        ["tenant_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_tenant_onboardings_tenant_id", "tenant_onboardings", ["tenant_id", "id"]
    )
    op.drop_constraint(
        op.f("tenant_onboardings_tenant_id_fkey"),
        "tenant_onboardings",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("tenant_onboardings_tenant_id_fkey"),
        "tenant_onboardings",
        "tenants",
        ["tenant_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_tenant_onboardings_tenant_id", "tenant_onboardings", type_="unique"
    )
    op.drop_index(
        op.f("ix_tenant_onboardings_tenant_id"), table_name="tenant_onboardings"
    )
    op.drop_constraint(
        "uq_payment_attempts_tenant_id", "payment_attempts", type_="unique"
    )
    op.drop_index(op.f("ix_payment_attempts_tenant_id"), table_name="payment_attempts")
    op.drop_index(op.f("ix_payment_attempts_invoice_id"), table_name="payment_attempts")
    op.drop_index(
        op.f("ix_payment_attempts_billing_account_id"), table_name="payment_attempts"
    )
    op.create_foreign_key(
        op.f("dunning_policies_tenant_id_fkey"),
        "dunning_policies",
        "tenants",
        ["tenant_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_dunning_policies_tenant_id", "dunning_policies", type_="unique"
    )
    op.drop_index(op.f("ix_dunning_policies_tenant_id"), table_name="dunning_policies")
    op.drop_constraint(
        "uq_data_import_rows_tenant_id", "data_import_rows", type_="unique"
    )
    op.drop_index(op.f("ix_data_import_rows_tenant_id"), table_name="data_import_rows")
    op.drop_index(op.f("ix_data_import_rows_batch_id"), table_name="data_import_rows")
    op.create_foreign_key(
        op.f("data_import_batches_tenant_id_fkey"),
        "data_import_batches",
        "tenants",
        ["tenant_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_data_import_batches_tenant_id", "data_import_batches", type_="unique"
    )
    op.drop_index(
        op.f("ix_data_import_batches_tenant_id"), table_name="data_import_batches"
    )
    # ### end Alembic commands ###
